### ISSUE TITLE
3 Issues

### ISSUE THREAD

**Issue by hashimthebeast** [BlockHorizons/PerWorldPlayer#11]
It cancels out preset items for lobby cores that use $player->getInventory()->setItem.

It also cancels out auto kitting example, when someone joins a specific world it automatically gives them a kit, per world player makes that not work

Last issue but not that important when someone does /reload per world player stops working like if its not there at all

**Comment by Muqsit** [comment]
Please report one bug per issue. The first and the second bugs are caused due to the same issue.
(1 & 2) Kit bug: Related to https://github.com/BlockHorizons/PerWorldPlayer/issues/4 (asynchronous inventory loading overwrites current inventory)
(3) Reload bug: https://github.com/BlockHorizons/PerWorldPlayer/issues/10
